- hosts: frontend
  tasks: 
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start and enable nginx upon reboot
      service: name=nginx enabled=yes state=started

    - name: Configure nginx as a load balancer
      template: src=nginx/lb.conf dest=/etc/nginx/sites-available/default
      notify:
        - restart nginx

  handlers:
    - name: restart php5-fpm
      service: name=php5-fpm state=restarted

    - name: restart nginx
      service: name=nginx state=restarted  

- hosts: backend
  tasks: 
    - name: install dummy nginx for testing
      apt: name=nginx state=latest

- hosts: backend1
  tasks: 
    - name: install dummy nginx for testing
      apt: name=nginx state=latest
    - name: Add nginx static file
      template: src=nginx/back1.html dest=/var/www/html/index.html
      notify:
        - restart nginx

  handlers:
    - name: restart php5-fpm
      service: name=php5-fpm state=restarted

    - name: restart nginx
      service: name=nginx state=restarted  

- hosts: backend2
  tasks: 
    - name: install dummy nginx for testing
      apt: name=nginx state=latest
    - name: Add nginx static file
      template: src=nginx/back2.html dest=/var/www/html/index.html
      notify:
        - restart nginx

  handlers:
  - name: restart php5-fpm
    service: name=php5-fpm state=restarted

  - name: restart nginx
    service: name=nginx state=restarted  
